### ISSUE TITLE
Feature request: Load replacements dict from url

### ISSUE THREAD

**Issue by danisztls** [ranisalt/neometal#1]
First things first. Thanks for the extension, it's funny. Face, you are much beast.

**How would it work?**
User inform an external URL to a JSON dict which will replace the `replacements` variable allowing him to customize the behaviour of the extensions. Extrally the extension could support multiple URLs at the same time. Lots of possibilities.

**Comment by ranisalt** [comment]
The problem is that the extension stores do not accept extensions that load data from an external service unless it is critical for their behavior, which is not the case. So, the extension would not be accepted.

**Comment by danisztls** [comment]
Ok.
